name: Build LaTeX CV
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: repaction/texlive@main
        with:
          tex_files: |
            CV Félix Piédallu.tex
