name: Build LaTeX CV
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true
          root_file: CV Félix Piédallu.tex

      - uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: CV Félix Piédallu.pdf
